spring:
  application:
    name: blog-search
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

client:
  kakao:
    url: https://dapi.kakao.com
    api-key: ""
  naver:
    url: https://openapi.naver.com
    api-id: ""
    api-secret: ""

resilience4j:
  circuitbreaker:
    configs:
      default:
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 4
        maxWaitDurationInHalfOpenState: 1000
    instances:
      blogSearch:
        base-config: default