spring:
  application:
    name: blog-search
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true

client:
  kakao:
    url: https://dapi.kakao.com
    api-key: ""
  naver:
    url: https://openapi.naver.com
    api-id: ""
    api-secret: ""